version: '3.7'

services:
  traefik:
    image: traefik:latest
    command: 
      #- "storeconfig" #This is the push to consul
      - "--logLevel=WARN"
      - "--api"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS TLS.SniStrict:true TLS.MinVersion:VersionTLS12 CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge=true"
      - "--acme.dnsChallenge.provider=godaddy"
      - "--acme.dnsChallenge.delayBeforeCheck=60"
      - "--acme.onHostRule=true"
      - "--acme.email=user@example.com"
      - "--acme.acmeLogging=true"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=domain.tld"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--retry"
    environment:
      TZ: America/New_York
#      CLOUDFLARE_EMAIL: user@example.com
#      CLOUDFLARE_API_KEY: gdfgdfsgdfg
      GODADDY_API_SECRET: sdfsdfsdfsdf
      GODADDY_API_KEY: sdfsdfsdfsdf
#      PROVIDER: godaddy
    ports:
      - target: 80
        published: 80
#        mode: host
      - target: 443
        published: 443
#        mode: host
      - target: 8080
        published: 8080
#        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /nfs/03cservices/traefik:/etc/traefik
      - /nfs/03cservices/docker/shared:/shared
      - /nfs/03cservices/traefik/acme/acme.json:/etc/traefik/acme/acme.json
      - /data/brick/traefik.log:/traefik.log
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        traefik.enable: "false"
        traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.entryPoint: http
        traefik.frontend.rule: Host:traefik.domain.tld,
        traefik.port: 8080
        traefik.protocol: http
        traefik.frontend.priority: 1
        traefik.backend: traefik
        traefik.docker.network: traefik
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSSeconds: 315360000
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.SSLHost: example.com
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.frameDeny: "true"
        traefik.frontend.auth.basic.users: xxx:xxx

networks:
  traefik:
    driver: overlay
    attachable: true
    name: traefik
    external: false
  external:
    driver: bridge
    attachable: true
    name: external
    external: false
