version: '3.7'

services:
  traefik:
    image: traefik:latest
    command: 
      #- "storeconfig" #This is the push to consul, secondary traefik must be created and interfaced to this traefik. Remove this traefik's open ports, it shuts down once consul is messaged.
      - "--logLevel=WARN"
      - "--api"
      - "--api.entrypoint=8080"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS TLS.SniStrict:true TLS.MinVersion:VersionTLS12 CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme.json"
      - "--acme.entryPoint=https"
# not yet ready?
#      - "--acme.TLS-ALPN-01=true"
      - "--acme.dnsChallenge=true"
      - "--acme.dnsChallenge.provider=godaddy"
      - "--acme.dnsChallenge.delayBeforeCheck=60"
      - "--acme.dnsChallenge.resolver=1.1.1.1"
      - "--acme.onHostRule=true"
      - "--acme.email=user@example.com"
      - "--acme.acmeLogging=true"
      - "--acme.domains=${DOMAINNAME},*${DOMAINNAME},"
      - "--acme.KeyType=RSA4096"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=${DOMAINNAME}"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--consul"
      - "--consul.endpoint=consul:8500"
      - "--consul.prefix=traefik"
      - "--retry"
      - "resolvers=[192,168.1.1:53,1.1.1.1:53,]"
    environment:
      TZ: ${TZ}
#      CLOUDFLARE_EMAIL: ${EMAIL}
#      CLOUDFLARE_API_KEY: ${CFKEY}
      GODADDY_API_SECRET: ${GODADDYSECRET}
      GODADDY_API_KEY: ${GODADDYKEY}
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
      - target: 8080
        published: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/traefik/acme.json:/etc/traefik/acme/acme.json
      - ${USERDIR}/traefik/traefik.log:/traefik.log
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      labels:
        traefik.enable: "true"
        traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
        traefik.frontend.redirect.entryPoint: https
        traefik.frontend.entryPoint: http
        traefik.frontend.rule: Host:traefik.${DOMAINNAME},
        traefik.port: 8080
        traefik.protocol: http
        traefik.frontend.priority: 1
        traefik.backend: traefik
        traefik.docker.network: traefik
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.frontend.headers.STSSeconds: 315360000
        traefik.frontend.headers.browserXSSFilter: "true"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.forceSTSHeader: "true"
        traefik.frontend.headers.SSLHost: traefik.${DOMAINNAME}
        traefik.frontend.headers.STSIncludeSubdomains: "true"
        traefik.frontend.headers.STSPreload: "true"
        traefik.frontend.headers.frameDeny: "true"
        traefik.frontend.headers.customFrameOptionsValue: 'allow-from https:${DOMAINNAME}'
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.headers.SSLForceHost: "true"
        #traefik.frontend.auth.forward.address: http://oauth:4181
        #traefik.frontend.auth.basic.users: xxx:xxx

networks:
  traefik:
    driver: overlay
    attachable: true
    name: traefik
    external: false
  external:
    driver: bridge
    attachable: true
    name: external
    external: false
